version: '3'

volumes:
  pg_data_kittygram:
  static_kittygram:
  media_kittygram:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data

  backend:
    env_file: .env
    image: rdayter/kittygram_backend
    volumes:
      - static_kittygram:/backend_static
      - media_kittygram:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: rdayter/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_kittygram:/static

  gateway:
    env_file: .env
    image: rdayter/kittygram_gateway
    ports:
      - 9000:80
    volumes:
      - static_kittygram:/static
      - media_kittygram:/media